name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^0.13.6
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/ticket.png
    - assets/cinta1.jpg
    - assets/cinta2.jpg
    - assets/cinta3.jpg
    - assets/spiderman.jpg
    - assets/endgame.jpg
    - assets/titanic.jpg
    - assets/lionking.jpg
    - assets/inception.jpg
    - assets/coco.jpg
    - assets/joker.jpg
    - assets/forrestgump.jpg
    - assets/jurassicpark.jpg
    - assets/toystory.jpg
    - assets/matrix.jpg
    - assets/blackpanther.jpg
    - assets/lalaland.jpg
    - assets/godfather.jpg
    - assets/frozen.jpg
    - assets/harrypotter1.jpg
    - assets/fast7.jpg
    - assets/encanto.jpg
    - assets/darkknight.jpg
    - assets/shrek.jpg
